version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=753951
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tracker
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db/shortcut/data:/var/lib/postgresql/data
    restart: always
  lb:
    build:
      context: .
      dockerfile: DockerfileLB
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/tracker
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=753951
      - JDBC_DRIVER=org.postgresql.Driver
    container_name: lb
    depends_on:
      - db
  job4j_tracker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/tracker
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=753951
      - JDBC_DRIVER=org.postgresql.Driver
    container_name: job4j_tracker
    depends_on:
      - db
      - lb